optimizations/improvements

diff --git a/scripts/rename b/scripts/rename
--- a/scripts/rename
+++ b/scripts/rename
@@ -1,13 +1,17 @@
 #!/bin/bash
 
-TARGET=$(realpath "$1")
+SOURCE=$(realpath "$1")
 
-if [ -f "$TARGET" ] || [ -d "$TARGET" ]; then
-    DEST=$(dirname "$TARGET")"/$2"
+if [ -f "$SOURCE" ] || [ -d "$SOURCE" ]; then
+    echo -n "Enter new name [$(basename "$SOURCE")]: " && read NEW_NAME 
 
-    mv "$TARGET" "$DEST"
-    
-    exit 0
+    if [[ ! -z $NEW_NAME ]]; then
+        mv "$SOURCE" "$(dirname "$SOURCE")/$NEW_NAME"
+        exit 0
+    fi
+
+    echo "Invalid new name!"
+    exit 2  
 fi
 
 echo "File not found!"
